# Select a base image:

FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime
RUN pip install thop imageio torchstat scipy dominate>=2.4.0 visdom>=0.1.8.8

# cd eval
# pkg install -forge image
# pkg load image
# main

